on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

  # MYSQL DB
  DB_MYSQL_DATABASE: test_sqlkata
  DB_MYSQL_USER: root
  DB_MYSQL_PASSWORD: "root"
  DB_MYSQL_HOST: localhost
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: dotnet build --configuration Release
      - name: Start MySql
        run: |
          sudo /etc/init.d/mysql start
          mysqladmin -u ${{ env.DB_MYSQL_USER }} -p${{ env.DB_MYSQL_PASSWORD }} password ''
          mysql -e 'CREATE DATABASE ${{ env.DB_MYSQL_DATABASE }};' -u${{ env.DB_MYSQL_USER }}
          mysql -e 'CREATE TABLE cars(id int primary key auto_increment);' -u${{ env.DB_MYSQL_USER }} ${{ env.DB_MYSQL_DATABASE }}
          mysql -e 'SHOW TABLES;' -u${{ env.DB_MYSQL_USER }} ${{ env.DB_MYSQL_DATABASE }}
      - name: Test
        run: dotnet test --configuration Release --no-build
        env:
          SQLKATA_MYSQL_HOST: ${{ env.DB_MYSQL_HOST }}
          SQLKATA_MYSQL_USER: ${{ env.DB_MYSQL_USER }}
          SQLKATA_MYSQL_DB: ${{ env.DB_MYSQL_DATABASE }}
